### ISSUE TITLE
Verify installer integrity fails

### ISSUE THREAD

**Issue by mmattel** [SoftCreatR/imei#30]
@SoftCreatR just wanted to do a integrity check and followed your instructions.

The check fails, because both of the files (signature and public key) return a 404.

Can you pls check and fix?

Many thanks

**Comment by SoftCreatR** [comment]
Should work now with the new instructions.

**Comment by mmattel** [comment]
Thanks that the files are now downloadable, but you still have an issue 😅 

You download the script to check
`wget https://dist.1-2.dev/imei`

But you check a different file
`openssl dgst -sha512 -verify public.pem -signature imei.sh.sig imei.sh`
`imei.sh` --> `imei` 

You just need to fix readme 😅 
Because you do not use the shell extension in One-Step Automated Install

**Comment by SoftCreatR** [comment]
Fixed that, too.

**Comment by mmattel** [comment]
finally...

bash <(curl -sL dist.1-2.dev/imei) 

imei --> imei.sh

😂

**Comment by SoftCreatR** [comment]
No, that's fine.
