### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by randomgithubuser1** [SoftCreatR/imei#37]
I have been using this script without issues, but is seems to be having an issue suddenly with signatures.  Running this inside a docker container using node:16-buster as base image.

```
root@ae7ab7a6f92a:/imei# ./imei.sh
 Signature verification failed!

 Please check /var/log/imei.log for details.
root@ae7ab7a6f92a:/imei# cat /var/log/imei.log
./imei.sh: line 283: : No such file or directory
./imei.sh: line 286: : No such file or directory
Can't open  for reading, No such file or directory
139795456062592:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('','r')
139795456062592:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
unable to load key file
```

**Comment by coandco** [comment]
I too am running into this, with the exact same error output.

**Comment by SoftCreatR** [comment]
Looks like I've accidentally removed two variables. Should be fixed in version 6.5.3.

**Comment by coandco** [comment]
This is still happening for me on debian:latest with a fresh checkout of imei:

```
root@c1d927b8c078:/imei# ./imei.sh
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists... Done
 Signature verification failed!

 Please check /var/log/imei.log for details.
root@c1d927b8c078:/imei# cat /var/log/imei.log
Verification Failure
```

**Comment by SoftCreatR** [comment]
That's correct. 6.5,3 hasn't been released, yet.

**Comment by SoftCreatR** [comment]
6.5.3 has just been released.

**Comment by coandco** [comment]
Ahh, thanks!  I can confirm that it works now.
